language: nix
os: osx
osx_image: xcode9.4
script:
- cat /etc/nix/nix.conf
- whoami
- echo "substituters = https://pact.cachix.org?trusted=1 https://nixcache.reflex-frp.org https://cache.nixos.org/" | sudo tee -a /etc/nix/nix.conf
- echo "trusted-public-keys = pact.cachix.org-1:cg1bsryGrHnQzqEp52NcHq4mBBL+R25XbR2Q/I/vQ8Y= ryantrinkle.com-1:JJiAKaRv9mWgpVAz8dwewnZe0AzzEAzPkagE9SP5NWI= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=" | sudo tee -a /etc/nix/nix.conf
- nix-build
