language: nix
os: osx
osx_image: xcode9.4
script:
- nix-build --substituters 'https://pact.cachix.org?trusted=1 https://nixcache.reflex-frp.org https://cache.nixos.org/' --trusted-public-keys 'pact.cachix.org-1:cg1bsryGrHnQzqEp52NcHq4mBBL+R25XbR2Q/I/vQ8Y= ryantrinkle.com-1:JJiAKaRv9mWgpVAz8dwewnZe0AzzEAzPkagE9SP5NWI= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY='
